= Spring Cloud Gateway - Customized Netty HTTP Client

== Run the Sample

* Build the sample -> `gradlew clean build`
* Run UAA Server -> `gradlew -b uaa-server/build.gradle uaa`
* Run Gateway -> `gradlew -b gateway/build.gradle bootRun`
* Go to `http://localhost:8080` and login to UAA using *user1/password*

When you hit URL, http://localhost:8080/, the gateway will go through OAuth2 flow and finally show Test OK page. See the logs in Gateway project sample.log, you will find line

r.n.resources.PooledConnectionProvider   : Creating a new client pool [PoolFactory {maxConnections=500, pendingAcquireMaxCount=-1, pendingAcquireTimeout=45000, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false}] for [localhost:8090]

Netty System Properties are defined in build.gradle of gateway project as below,

bootRun {
        systemProperty "reactor.netty.pool.maxIdleTime", "600000"
        systemProperty "reactor.netty.pool.leasingStrategy", "lifo"
}

That means the customization on Netty Pool above does not take effective.
